#!/bin/bash

export BEMPP_ROOT=/unicluster/home/matvey.kraposhin/run/bempp

export BEMPP_INSTALL_ROOT=$BEMPP_ROOT/Install

export PATH=$BEMPP_INSTALL_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$BEMPP_INSTALL_ROOT/lib:$LD_LIBRARY_PATH
export PYTHONPATH=$BEMPP_INSTALL_ROOT/lib/python2.7

export CPLUS_INCLUDE_PATH=$BEMPP_INSTALL_ROOT/include
export C_INCLUDE_PATH=$BEMPP_INSTALL_ROOT/include

export EIGEN3_INCLUDE_DIR=$BEMPP_INSTALL_ROOT/include

TBBROOT=$BEMPP_INSTALL_ROOT
export TBB_LIBRARY_DIR=$TBBROOT/lib
export TBB_INCLUDE_DIR=$TBBROOT/include/tbb

#
#END-OF-FILE
#


